# FROM alpine:3.14


# RUN apk add --update alpine-sdk && apk add --no-cache build-base \
#     && apk add ruby-full ruby-dev && gem install bundler && bundle update --bundler && bundle

# ADD Gemfile* $APP_HOME/
# # RUN bundle add
# ADD . $APP_HOME

# ENV POST_SERVICE_HOST post
# ENV POST_SERVICE_PORT 5000
# ENV COMMENT_SERVICE_HOST comment
# ENV COMMENT_SERVICE_PORT 9292

# CMD ["puma"]

FROM alpine:3.14

RUN apk add --update alpine-sdk && apk add --no-cache build-base \
    && apk add ruby-full ruby-dev
ENV APP_HOME /app
RUN mkdir $APP_HOME

WORKDIR $APP_HOME
ADD Gemfile* $APP_HOME/
RUN bundle update --bundler && gem install bundler && bundle install
ADD . $APP_HOME

ENV POST_SERVICE_HOST post
ENV POST_SERVICE_PORT 5000
ENV COMMENT_SERVICE_HOST comment
ENV COMMENT_SERVICE_PORT 9292

CMD ["puma"]
