version: "3.3"
services:
  post_db:
    image: mongo:${mongodb_version}
    volumes:
      - post_db:${path_to_db}
    networks:
      - back_net
  ui:
    build: src/ui
    image: ${USER_NAME}/ui:1.0
    ports:
      - ${port}:${port}/tcp
    networks:
      - front_net
  post:
    build: src/post-py
    image: ${USER_NAME}/post:1.0
    networks:
      - back_net
      - front_net
  comment:
    build: src/comment
    image: ${USER_NAME}/comment:1.0
    networks:
      - back_net
      - front_net

  prometheus:
    image: ${USER_NAME}/prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command: # Передаем доп параметры в командной строке
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d' # Задаем время хранения метрик в 1 день
    networks:
      - back_net
      - front_net

volumes:
  post_db:
  prometheus_data:

networks:
  back_net:
  front_net:
