# 1) Изменить docker-compose под кейс с множеством сетей,
# сетевых алиасов (стр 18).

# Параметризуйте с помощью переменных окружений:
# • порт публикации сервиса ui
# • версии сервисов
# • возможно что-либо еще на ваше усмотрение

version: "3.3"
services:
  post_db:
    image: mongo:${mongodb_version}
    volumes:
      - post_db:${path_to_db}
    networks:
      - back_net
  ui:
    build: ./ui
    image: ${USERNAME}/ui:1.0
    ports:
      - ${port}:${port}/tcp
    networks:
      - front_net
  post:
    build: ./post-py
    image: ${USERNAME}/post:1.0
    networks:
      - back_net
      - front_net
  comment:
    build: ./comment
    image: ${USERNAME}/comment:1.0
    networks:
      - back_net
      - front_net

volumes:
  post_db:

networks:
  back_net:
  front_net:
